-- DROP USER JAVAZON;

CREATE USER JAVAZON
-- IDENTIFIED BY <password>
;

CREATE TABLE "JAVAZON"."CART"
   (	"CART_ID" NUMBER,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"CREATED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "JAVAZON"."CART" ADD CONSTRAINT "FK_CART_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "JAVAZON"."USERS" ("USER_ID") ENABLE;

CREATE OR REPLACE TRIGGER "JAVAZON"."CART_PK_SEQ"
BEFORE INSERT ON CART
FOR EACH ROW
BEGIN
    IF :NEW.CART_ID IS NULL THEN
        SELECT CART_SEQ.NEXTVAL INTO :NEW.CART_ID FROM dual;
    END IF;
END;
/
/
ALTER TRIGGER "JAVAZON"."CART_PK_SEQ" ENABLE;

CREATE UNIQUE INDEX "JAVAZON"."SYS_C007038" ON "JAVAZON"."CART" ("CART_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "JAVAZON"."CART_ITEM"
   (	"CART_ITEM_ID" NUMBER,
	"CART_ID" NUMBER NOT NULL ENABLE,
	"PRODUCT_ID" NUMBER NOT NULL ENABLE,
	"QUANTITY" NUMBER DEFAULT 1,
	"ADDED_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 PRIMARY KEY ("CART_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "JAVAZON"."CART_ITEM" ADD CONSTRAINT "FK_CARTITEM_CART" FOREIGN KEY ("CART_ID")
	  REFERENCES "JAVAZON"."CART" ("CART_ID") ENABLE;
  ALTER TABLE "JAVAZON"."CART_ITEM" ADD CONSTRAINT "FK_CARTITEM_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "JAVAZON"."PRODUCT" ("PRODUCT_ID") ENABLE;

CREATE OR REPLACE TRIGGER "JAVAZON"."CART_ITEM_PK_SEQ"
BEFORE INSERT ON CART_ITEM
FOR EACH ROW
BEGIN
    IF :NEW.CART_ITEM_ID IS NULL THEN
        SELECT CART_ITEM_SEQ.NEXTVAL INTO :NEW.CART_ITEM_ID FROM dual;
    END IF;
END;
/

/
ALTER TRIGGER "JAVAZON"."CART_ITEM_PK_SEQ" ENABLE;

CREATE UNIQUE INDEX "JAVAZON"."SYS_C007042" ON "JAVAZON"."CART_ITEM" ("CART_ITEM_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "JAVAZON"."ORDERS"
   (	"ORDER_ID" NUMBER,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"ORDER_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"TOTAL_AMOUNT" NUMBER(10,2) NOT NULL ENABLE,
	"STATUS" VARCHAR2(50) DEFAULT 'PENDING',
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

ALTER TABLE "JAVAZON"."ORDERS" ADD CONSTRAINT "FK_ORDERS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "JAVAZON"."USERS" ("USER_ID") ENABLE;

CREATE OR REPLACE TRIGGER "JAVAZON"."ORDERS_PK_SEQ"
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM dual;
    END IF;
END;
/
/
ALTER TRIGGER "JAVAZON"."ORDERS_PK_SEQ" ENABLE;

CREATE UNIQUE INDEX "JAVAZON"."SYS_C007047" ON "JAVAZON"."ORDERS" ("ORDER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE TABLE "JAVAZON"."PRODUCT"
   (	"PRODUCT_ID" NUMBER,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" CLOB,
	"PRICE" NUMBER(10,2) NOT NULL ENABLE,
	"STOCK_QUANTITY" NUMBER,
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE OR REPLACE TRIGGER "JAVAZON"."PRODUCT_PK_SEQ"
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    IF :NEW.PRODUCT_ID IS NULL THEN
        SELECT PRODUCT_SEQ.NEXTVAL INTO :NEW.PRODUCT_ID FROM dual;
    END IF;
END;
/
ALTER TRIGGER "JAVAZON"."PRODUCT_PK_SEQ" ENABLE;

CREATE UNIQUE INDEX "JAVAZON"."SYS_C007036" ON "JAVAZON"."PRODUCT" ("PRODUCT_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "JAVAZON"."SYS_IL0000020365C00003$$" ON "JAVAZON"."PRODUCT" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
;

CREATE TABLE "JAVAZON"."USERS"
   (	"USER_ID" NUMBER,
	"USERNAME" VARCHAR2(10) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(50),
	"LAST_NAME" VARCHAR2(50),
	 PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

CREATE OR REPLACE TRIGGER "JAVAZON"."USERS_PK_SEQ"
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.USER_ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.USER_ID FROM dual;
  END IF;
END;
/
ALTER TRIGGER "JAVAZON"."USERS_PK_SEQ" ENABLE;

CREATE UNIQUE INDEX "JAVAZON"."SYS_C007027" ON "JAVAZON"."USERS" ("USER_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "JAVAZON"."SYS_C007028" ON "JAVAZON"."USERS" ("USERNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  CREATE UNIQUE INDEX "JAVAZON"."SYS_C007029" ON "JAVAZON"."USERS" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
;

CREATE SEQUENCE JAVAZON.CART_ITEM_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE JAVAZON.CART_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE JAVAZON.ORDERS_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE JAVAZON.PRODUCT_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE JAVAZON.SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER ;

CREATE SEQUENCE JAVAZON.USERS_SEQ INCREMENT BY 1 MINVALUE 0 MAXVALUE 1000000 NOCYCLE NOCACHE NOORDER ;-- Hello, This is Mohamed Elharby